export const data = [
  ['Uno', 'One'],
  ['Dos', 'Two'],
  ['Tres', 'Three'],
  ['Cuatro', 'Four'],
];

export const dataFull = [
  ['de', 'of'],
  ['la', 'the'],
  ['que', 'that'],
  ['el', 'the'],
  ['en', 'in'],
  ['y', 'and'],
  ['a', 'to'],
  ['los', 'the'],
  ['del', 'of the'],
  ['se', 'self, oneself'],
  ['las', 'the'],
  ['por', 'for'],
  ['un', 'a'],
  ['para', 'for'],
  ['con', 'with'],
  ['no', 'no'],
  ['una', 'a'],
  ['su', 'his/her/its/their'],
  ['al', 'to the'],
  ['lo', 'it'],
  ['como', 'like'],
  ['más', 'more'],
  ['pero', 'but'],
  ['sus', 'his/her/its/their'],
  ['le', 'to him/her'],
  ['ya', 'already'],
  ['o', 'or'],
  ['este', 'this'],
  ['sí', 'yes'],
  ['porque', 'because'],
  ['esta', 'this'],
  ['entre', 'between'],
  ['cuando', 'when'],
  ['muy', 'very'],
  ['sin', 'without'],
  ['sobre', 'on'],
  ['también', 'also'],
  ['me', 'me'],
  ['hasta', 'until'],
  ['hay', 'there is/are'],
  ['donde', 'where'],
  ['quien', 'who'],
  ['desde', 'from'],
  ['todo', 'all'],
  ['nos', 'us'],
  ['durante', 'during'],
  ['todos', 'all'],
  ['uno', 'one'],
  ['les', 'to them'],
  ['ni', 'neither'],
  ['contra', 'against'],
  ['otros', 'others'],
  ['ese', 'that'],
  ['eso', 'that'],
  ['ante', 'before'],
  ['ellos', 'they/them'],
  ['e', 'and'],
  ['esto', 'this'],
  ['mí', 'me'],
  ['antes', 'before'],
  ['algunos', 'some'],
  ['qué', 'what'],
  ['unos', 'some'],
  ['yo', 'I'],
  ['otro', 'other'],
  ['otras', 'other'],
  ['otra', 'other'],
  ['él', 'he'],
  ['tanto', 'so much'],
  ['esa', 'that'],
  ['estos', 'these'],
  ['mucho', 'much'],
  ['quienes', 'who'],
  ['nada', 'nothing'],
  ['muchos', 'many'],
  ['cual', 'which'],
  ['poco', 'little'],
  ['ella', 'she'],
  ['estar', 'to be'],
  ['estas', 'these'],
  ['algunas', 'some'],
  ['algo', 'something'],
  ['nosotros', 'we'],
  ['mi', 'my'],
  ['mis', 'my'],
  ['tú', 'you'],
  ['te', 'you'],
  ['ti', 'you'],
  ['tu', 'your'],
  ['tus', 'your'],
  ['ellas', 'they/them'],
  ['nosotras', 'we'],
  ['vosotros', 'you all'],
  ['vosotras', 'you all'],
  ['os', 'you all'],
  ['mío', 'mine'],
  ['mía', 'mine'],
  ['míos', 'mine'],
  ['mías', 'mine'],
  ['tuyo', 'yours'],
  ['tuya', 'yours'],
  ['tuyos', 'yours'],
  ['tuyas', 'yours'],
  ['suyo', 'his/her/its/their'],
  ['suya', 'his/her/its/their'],
  ['suyos', 'his/her/its/their'],
  ['suyas', 'his/her/its/their'],
  ['nuestro', 'our'],
  ['nuestra', 'our'],
  ['nuestros', 'our'],
  ['nuestras', 'our'],
  ['vuestro', 'your'],
  ['vuestra', 'your'],
  ['vuestros', 'your'],
  ['vuestras', 'your'],
  ['esos', 'those'],
  ['esas', 'those'],
  ['estoy', 'I am'],
  ['estás', 'you are'],
  ['está', 'he/she/it is'],
  ['estamos', 'we are'],
  ['estáis', 'you all are'],
  ['están', 'they are'],
  ['esté', 'be'],
  ['estés', 'be'],
  ['estemos', 'be'],
  ['estéis', 'be'],
  ['estén', 'be'],
  ['estaré', 'I will be'],
  ['estarás', 'you will be'],
  ['estará', 'he/she/it will be'],
  ['estaremos', 'we will be'],
  ['estaréis', 'you all will be'],
  ['estarán', 'they will be'],
  ['ser', 'to be (permanent)'],
  ['soy', 'I am'],
  ['eres', 'you are'],
  ['es', 'he/she/it is'],
  ['somos', 'we are'],
  ['sois', 'you all are'],
  ['son', 'they are'],
  ['sea', 'be'],
  ['seas', 'be'],
  ['seamos', 'be'],
  ['seáis', 'be'],
  ['sean', 'be'],
  ['seré', 'I will be'],
  ['serás', 'you will be'],
  ['será', 'he/she/it will be'],
  ['seremos', 'we will be'],
  ['seréis', 'you all will be'],
  ['serán', 'they will be'],
  ['tengo', 'I have'],
  ['tienes', 'you have'],
  ['tiene', 'he/she/it has'],
  ['tenemos', 'we have'],
  ['tenéis', 'you all have'],
  ['tienen', 'they have'],
  ['el cual', 'which'],
  ['la cual', 'which'],
  ['los cuales', 'which'],
  ['las cuales', 'which'],
  ['cuyo', 'whose'],
  ['cuya', 'whose'],
  ['cuyos', 'whose'],
  ['cuyas', 'whose'],
  ['que', 'that'],
  ['quien', 'who'],
  ['quienes', 'who'],
  ['cuál', 'which/what'],
  ['cuáles', 'which/what'],
  ['cuando', 'when'],
  ['cuánto', 'how much'],
  ['cuánta', 'how much'],
  ['cuántos', 'how many'],
  ['cuántas', 'how many'],
  ['dónde', 'where'],
  ['cómo', 'how'],
  ['por qué', 'why'],
  ['para qué', 'what for'],
  ['aunque', 'although'],
  ['como', 'like/as'],
  ['si', 'if'],
  ['sino', 'but rather'],
  ['como si', 'as if'],
  ['que', 'that/which'],
  ['quién', 'who'],
  ['quienes', 'who'],
  ['cuál', 'which/what'],
  ['cuáles', 'which/what'],
  ['cuándo', 'when'],
  ['cuánto', 'how much'],
  ['cuánta', 'how much'],
  ['cuántos', 'how many'],
  ['cuántas', 'how many'],
  ['dónde', 'where'],
  ['cómo', 'how'],
  ['por qué', 'why'],
  ['para qué', 'what for'],
  ['aunque', 'although'],
  ['como', 'like/as'],
  ['si', 'if'],
  ['sino', 'but rather'],
  ['como si', 'as if'],
  ['yendo', 'going'],
  ['ido', 'gone'],
  ['estar', 'to be'],
  ['teniendo', 'having'],
  ['tenido', 'had'],
  ['haciendo', 'doing'],
  ['hecho', 'done'],
  ['diciendo', 'saying'],
  ['dicho', 'said'],
  ['viendo', 'seeing'],
  ['visto', 'seen'],
  ['sabiendo', 'knowing'],
  ['sabido', 'known'],
  ['querer', 'to want/love'],
  ['querría', 'I would want/love'],
  ['querido', 'wanted/loved'],
  ['poder', 'to be able to'],
  ['podría', 'I could'],
  ['podido', 'been able to'],
  ['deber', 'to have to'],
  ['debería', 'I should'],
  ['debido', 'had to'],
  ['haber', 'to have'],
  ['habría', 'I would have'],
  ['habido', 'I would have gone'],
  ['habiendo', 'having (participle)'],
  ['habido', 'had (participle)'],
  ['decir', 'to say/tell'],
  ['diría', 'I would say/tell'],
  ['dicho', 'said/told'],
  ['dar', 'to give'],
  ['daría', 'I would give'],
  ['dado', 'given'],
  ['ver', 'to see'],
  ['vería', 'I would see'],
  ['visto', 'seen'],
  ['saber', 'to know'],
  ['sabría', 'I would know'],
  ['sabido', 'known'],
  ['ir', 'to go'],
  ['iría', 'I would go'],
  ['ido', 'gone'],
  ['hacer', 'to do/make'],
  ['haría', 'I would do/make'],
  ['hecho', 'done/made'],
  ['pensar', 'to think'],
  ['pensaría', 'I would think'],
  ['pensado', 'thought'],
  ['creer', 'to believe'],
  ['creería', 'I would believe'],
  ['creído', 'believed'],
  ['sentir', 'to feel'],
  ['sentiría', 'I would feel'],
  ['sentido', 'felt'],
  ['conocer', 'to know/meet'],
  ['conocería', 'I would know/meet'],
  ['conocido', 'known/met'],
  ['querer', 'to want/love'],
  ['querría', 'I would want/love'],
  ['querido', 'wanted/loved'],
  ['tener', 'to have'],
  ['tendría', 'I would have'],
  ['tenido', 'had'],
  ['deber', 'to have to'],
  ['debería', 'I should'],
  ['debido', 'had to'],
  ['poder', 'to be able to'],
  ['podría', 'I could'],
  ['podido', 'been able to'],
  ['decir', 'to say/tell'],
  ['diría', 'I would say/tell'],
  ['dicho', 'said/told'],
  ['dar', 'to give'],
  ['daría', 'I would give'],
  ['dado', 'given'],
  ['ver', 'to see'],
  ['vería', 'I would see'],
  ['visto', 'seen'],
  ['saber', 'to know'],
  ['sabría', 'I would know'],
  ['sabido', 'known'],
  ['ir', 'to go'],
  ['iría', 'I would go'],
  ['ido', 'gone'],
  ['hacer', 'to do/make'],
  ['haría', 'I would do/make'],
  ['hecho', 'done/made'],
  ['pensar', 'to think'],
  ['pensaría', 'I would think'],
  ['pensado', 'thought'],
  ['creer', 'to believe'],
  ['creería', 'I would believe'],
  ['creído', 'believed'],
  ['sentir', 'to feel'],
  ['sentiría', 'I would feel'],
  ['sentido', 'felt'],
  ['conocer', 'to know/meet'],
  ['conocería', 'I would know/meet'],
  ['conocido', 'known/met'],
  ['venir', 'to come'],
  ['vendría', 'I would come'],
  ['venido', 'come'],
  ['tomar', 'to take/drink'],
  ['tomaría', 'I would take/drink'],
  ['tomado', 'taken/drunk'],
  ['decir', 'to say/tell'],
  ['decía', 'I was saying/telling'],
  ['dijo', 'he/she/it said/told'],
  ['diciendo', 'saying/telling (participle)'],
  ['poder', 'to be able to'],
  ['podía', 'I was able to/could'],
  ['pudo', 'he/she/it was able to/could'],
  ['hacer', 'to do/make'],
  ['hacía', 'I was doing/making'],
  ['hizo', 'he/she/it did/made'],
  ['haber', 'to have (auxiliary)'],
  ['había', 'there was/had (imperfect)'],
  ['habían', 'there were/had (imperfect)'],
  ['habría', 'there would be/have (conditional)'],
  ['tener', 'to have'],
  ['tenía', 'I had (imperfect)'],
  ['tenían', 'they had (imperfect)'],
  ['tendría', 'I would have (conditional)'],
  ['ser', 'to be (essential quality)'],
  ['era', 'I/he/she/it was (imperfect)'],
  ['eras', 'you were (imperfect)'],
  ['eran', 'they were (imperfect)'],
  ['sería', 'I/he/she/it would be (conditional)'],
  ['estar', 'to be (temporary state/condition)'],
  ['estaba', 'I/he/she/it was (imperfect)'],
  ['estás', 'you are (present)'],
  ['estaban', 'they were (imperfect)'],
  ['estaría', 'I/he/she/it would be (conditional)'],
  ['hablar', 'to speak'],
  ['hablaba', 'I was speaking (imperfect)'],
  ['hablas', 'you speak (present)'],
  ['hablaban', 'they were speaking (imperfect)'],
  ['hablaría', 'I/he/she/it would speak (conditional)'],
  ['decir', 'to say/tell'],
  ['decía', 'I was saying/telling (imperfect)'],
  ['dices', 'you say/tell (present)'],
  ['decían', 'they were saying/telling (imperfect)'],
  ['diría', 'I/he/she/it would say/tell (conditional)'],
  ['tener', 'to have'],
  ['tengo', 'I have (present)'],
  ['tienes', 'you have (present)'],
  ['tienen', 'they have (present)'],
  ['teniendo', 'having (participle)'],
  ['tenido', 'had (participle)'],
  ['dar', 'to give'],
  ['doy', 'I give (present)'],
  ['da', 'he/she/it gives (present)'],
  ['dan', 'they give (present)'],
  ['dando', 'giving (participle)'],
  ['dado', 'given (participle)'],
  ['ver', 'to see'],
  ['veo', 'I see (present)'],
  ['ves', 'you see (present)'],
  ['ven', 'they see (present)'],
  ['viendo', 'seeing (participle)'],
  ['visto', 'seen (participle)'],
  ['ir', 'to go'],
  ['voy', 'I go (present)'],
  ['vas', 'you go (present)'],
  ['van', 'they go (present)'],
  ['yendo', 'going (participle)'],
  ['ido', 'gone (participle)'],
  ['saber', 'to know'],
  ['sé', 'I know (present)'],
  ['sabes', 'you know (present)'],
  ['saben', 'they know (present)'],
  ['sabiendo', 'knowing (participle)'],
  ['sabido', 'known (participle)'],
  ['poder', 'to be able to'],
  ['puedo', 'I can (present)'],
  ['puedes', 'you can (present)'],
  ['pueden', 'they can (present)'],
  ['pudiendo', 'being able to (participle)'],
  ['podido', 'been able to (participle)'],
  ['querer', 'to want/love'],
  ['quiero', 'I want/love (present)'],
  ['quieres', 'you want/love (present)'],
  ['quieren', 'they want/love (present)'],
  ['queriendo', 'wanting/loving (participle)'],
  ['querido', 'wanted/loved (participle)'],
  ['creer', 'to believe'],
  ['creo', 'I believe (present)'],
  ['crees', 'you believe (present)'],
  ['creen', 'they believe (present)'],
  ['creyendo', 'believing (participle)'],
  ['creído', 'believed (participle)'],
  ['deber', 'toshould/must/ought to'],
  ['debo', 'I should/must/ought to (present)'],
  ['debes', 'you should/must/ought to (present)'],
  ['deben', 'they should/must/ought to (present)'],
  ['debiendo', 'having to/ought to (participle)'],
  ['debido', 'had to/ought to (participle)'],
  ['hacer', 'to do/make'],
  ['hago', 'I do/make (present)'],
  ['haces', 'you do/make (present)'],
  ['hacen', 'they do/make (present)'],
  ['haciendo', 'doing/making (participle)'],
  ['hecho', 'done/made (participle)'],
  ['decir', 'to say/tell'],
  ['digo', 'I say/tell (present)'],
  ['dices', 'you say/tell (present)'],
  ['dicen', 'they say/tell (present)'],
  ['diciendo', 'saying/telling (participle)'],
  ['dicho', 'said/told (participle)'],
  ['ver', 'to see'],
  ['veo', 'I see (present)'],
  ['ves', 'you see (present)'],
  ['ven', 'they see (present)'],
  ['viendo', 'seeing (participle)'],
  ['visto', 'seen (participle)'],
  ['saber', 'to know'],
  ['sé', 'I know (present)'],
  ['sabes', 'you know (present)'],
  ['saben', 'they know (present)'],
  ['sabiendo', 'knowing (participle)'],
  ['sabido', 'known (participle)'],
  ['poner', 'to put/place'],
  ['pongo', 'I put/place (present)'],
  ['pones', 'you put/place (present)'],
  ['ponen', 'they put/place (present)'],
  ['poniendo', 'putting/placing (participle)'],
  ['puesto', 'put/placed (participle)'],
  ['salir', 'to go out/leave'],
  ['salgo', 'I go out/leave (present)'],
  ['sales', 'you go out/leave (present)'],
  ['salen', 'they go out/leave (present)'],
  ['saliendo', 'going out/leaving (participle)'],
  ['salido', 'gone out/left (participle)'],
  ['conocer', 'to know/be familiar with'],
  ['conozco', 'I know/am familiar with (present)'],
  ['conoces', 'you know/are familiar with (present)'],
  ['conocen', 'they know/are familiar with (present)'],
  ['conociendo', 'knowing/being familiar with (participle)'],
  ['conocido', 'known/familiar (participle)'],
  ['llevar', 'to carry/wear/take'],
  ['llevo', 'I carry/wear/take (present)'],
  ['llevas', 'you carry/wear/take (present)'],
  ['llevan', 'they carry/wear/take (present)'],
  ['llevando', 'carrying/wearing/taking (participle)'],
  ['llevado', 'carried/worn/taken (participle)'],
  ['sentir', 'to feel/regret'],
  ['siento', 'I feel/regret (present)'],
  ['sientes', 'you feel/regret (present)'],
  ['sienten', 'they feel/regret (present)'],
  ['sintiendo', 'feeling/regretting (participle)'],
  ['sentido', 'felt/regretted (participle)'],
  ['empezar', 'to start/begin'],
  ['empiezo', 'I start/begin (present)'],
  ['empiezas', 'you start/begin (present)'],
  ['empiezan', 'they start/begin (present)'],
  ['empezando', 'starting/beginning (participle)'],
  ['empezado', 'started/begun (participle)'],
  ['tratar', 'to try/treat'],
  ['trato', 'I try/treat (present)'],
  ['tratas', 'you try/treat (present)'],
  ['tratan', 'they try/treat (present)'],
  ['tratando', 'trying/treating (participle)'],
  ['tratado', 'tried/treated (participle)'],
  ['trabajar', 'to work'],
  ['trabajo', 'I work (present)'],
  ['trabajas', 'you work (present)'],
  ['trabajan', 'they work (present)'],
  ['trabajando', 'working (participle)'],
  ['trabajado', 'worked (participle)'],
  ['parecer', 'to seem/appear'],
  ['parezco', 'I seem/appear (present)'],
  ['pareces', 'you seem/appear (present)'],
  ['parecen', 'they seem/appear (present)'],
  ['pareciendo', 'seeming/appearing (participle)'],
  ['parecido', 'seemed/appeared (participle)'],
  ['poder', 'to be able to/can'],
  ['puedo', 'I am able to/can (present)'],
  ['puedes', 'you are able to/can (present)'],
  ['pueden', 'they are able to/can (present)'],
  ['pudiendo', 'being able to/can (participle)'],
  ['podido', 'been able to/could (participle)'],
  ['querer', 'to want/love'],
  ['quiero', 'I want/love (present)'],
  ['quieres', 'you want/love (present)'],
  ['quieren', 'they want/love (present)'],
  ['queriendo', 'wanting/loving (participle)'],
  ['querido', 'wanted/loved (participle)'],
  ['decidir', 'to decide'],
  ['decido', 'I decide (present)'],
  ['decides', 'you decide (present)'],
  ['deciden', 'they decide (present)'],
  ['decidiendo', 'deciding (participle)'],
  ['decidido', 'decided (participle)'],
  ['llegar', 'to arrive/come'],
  ['llego', 'I arrive/come (present)'],
  ['llegas', 'you arrive/come (present)'],
  ['llegan', 'they arrive/come (present)'],
  ['llegando', 'arriving/coming (participle)'],
  ['llegado', 'arrived/come (participle)'],
  ['buscar', 'to look for/search'],
  ['busco', 'I look for/search (present)'],
  ['buscas', 'you look for/search (present)'],
  ['buscan', 'they look for/search (present)'],
  ['buscando', 'looking for/searching (participle)'],
  ['buscado', 'looked for/searched (participle)'],
  ['creer', 'to believe'],
  ['creo', 'I believe (present)'],
  ['crees', 'you believe (present)'],
  ['creen', 'they believe (present)'],
  ['creyendo', 'believing (participle)'],
  ['creído', 'believed (participle)'],
  ['comenzar', 'to begin/start'],
  ['comienzo', 'I begin/start (present)'],
  ['comienzas', 'you begin/start (present)'],
  ['comienzan', 'they begin/start (present)'],
  ['comenzando', 'beginning/starting (participle)'],
  ['comenzado', 'begun/started (participle)'],
  ['encontrar', 'to find'],
  ['encuentro', 'I find (present)'],
  ['encuentras', 'you find (present)'],
  ['encuentran', 'they find (present)'],
  ['encontrando', 'finding (participle)'],
  ['encontrado', 'found (participle)'],
  ['pensar', 'to think'],
  ['pienso', 'I think (present)'],
  ['piensas', 'you think (present)'],
  ['piensan', 'they think (present)'],
  ['pensando', 'thinking (participle)'],
  ['pensado', 'thought (participle)'],
  ['entender', 'to understand'],
  ['entiendo', 'I understand (present)'],
  ['entiendes', 'you understand (present)'],
  ['entienden', 'they understand (present)'],
  ['entendiendo', 'understanding (participle)'],
  ['entendido', 'understood (participle)'],
  ['vivir', 'to live'],
  ['vivo', 'I live (present)'],
  ['vives', 'you live (present)'],
  ['viven', 'they live (present)'],
  ['viviendo', 'living (participle)'],
  ['vivido', 'lived (participle)'],
  ['sentir', 'to feel/regret'],
  ['siento', 'I feel/regret (present)'],
  ['sientes', 'you feel/regret (present)'],
  ['sienten', 'they feel/regret (present)'],
  ['sintiendo', 'feeling/regretting (participle)'],
  ['sentido', 'felt/regretted (participle)'],
  ['llevar', 'to carry/wear/take'],
  ['llevo', 'I carry/wear/take (present)'],
  ['llevas', 'you carry/wear/take (present)'],
  ['llevan', 'they carry/wear/take (present)'],
  ['llevando', 'carrying/wearing/taking (participle)'],
  ['llevado', 'carried/worn/taken (participle)'],
  ['dejar', 'to leave/let'],
  ['dejo', 'I leave/let (present)'],
  ['dejas', 'you leave/let (present)'],
  ['dejan', 'they leave/let (present)'],
  ['dejando', 'leaving/letting (participle)'],
  ['dejado', 'left/let (participle)'],
  ['necesitar', 'to need'],
  ['necesito', 'I need (present)'],
  ['necesitas', 'you need (present)'],
  ['necesitan', 'they need (present)'],
  ['necesitando', 'needing (participle)'],
  ['necesitado', 'needed (participle)'],
  ['llevar', 'to carry/take/wear'],
  ['llevo', 'I carry/take/wear (present)'],
  ['llevas', 'you carry/take/wear (present)'],
  ['llevan', 'they carry/take/wear (present)'],
  ['llevando', 'carrying/taking/wearing (participle)'],
  ['llevado', 'carried/taken/worn (participle)'],
  ['volver', 'to return/come back'],
  ['vuelvo', 'I return/come back (present)'],
  ['vuelves', 'you return/come back (present)'],
  ['vuelven', 'they return/come back (present)'],
  ['volviendo', 'returning/coming back (participle)'],
  ['vuelto', 'returned/come back (participle)'],
  ['empezar', 'to start/begin'],
  ['empiezo', 'I start/begin (present)'],
  ['empiezas', 'you start/begin (present)'],
  ['empiezan', 'they start/begin (present)'],
  ['empezando', 'starting/beginning (participle)'],
  ['empezado', 'started/begun (participle)'],
  ['tratar', 'to try/treat'],
  ['trato', 'I try/treat (present)'],
  ['tratas', 'you try/treat (present)'],
  ['tratan', 'they try/treat (present)'],
  ['tratando', 'trying/treating (participle)'],
  ['tratado', 'tried/treated (participle)'],
  ['trabajar', 'to work'],
  ['trabajo', 'I work (present)'],
  ['trabajas', 'you work (present)'],
  ['trabajan', 'they work (present)'],
  ['trabajando', 'working (participle)'],
  ['trabajado', 'worked (participle)'],
  ['poder', 'to be able to/can'],
  ['puedo', 'I can (present)'],
  ['puedes', 'you can (present)'],
  ['pueden', 'they can (present)'],
  ['pudiendo', 'being able to/can (participle)'],
  ['podido', 'been able to/can (participle)'],
  ['querer', 'to want/love'],
  ['quiero', 'I want/love (present)'],
  ['quieres', 'you want/love (present)'],
  ['quieren', 'they want/love (present)'],
  ['queriendo', 'wanting/loving (participle)'],
  ['querido', 'wanted/loved (participle)'],
  ['saber', 'to know'],
  ['sé', 'I know (present)'],
  ['sabes', 'you know (present)'],
  ['saben', 'they know (present)'],
  ['sabiendo', 'knowing (participle)'],
  ['sabido', 'known (participle)'],
  ['dar', 'to give'],
  ['doy', 'I give (present)'],
  ['das', 'you give (present)'],
  ['dan', 'they give (present)'],
  ['dando', 'giving (participle)'],
  ['dado', 'given (participle)'],
  ['venir', 'to come'],
  ['vengo', 'I come (present)'],
  ['vienes', 'you come (present)'],
  ['vienen', 'they come (present)'],
  ['viniendo', 'coming (participle)'],
  ['venido', 'come (participle)'],
  ['decir', 'to say/tell'],
  ['digo', 'I say/tell (present)'],
  ['dices', 'you say/tell (present)'],
  ['dicen', 'they say/tell (present)'],
  ['diciendo', 'saying/telling (participle)'],
  ['dicho', 'said/told (participle)'],
  ['ver', 'to see'],
  ['veo', 'I see (present)'],
  ['ves', 'you see (present)'],
  ['ven', 'they see (present)'],
  ['viendo', 'seeing (participle)'],
  ['visto', 'seen (participle)'],
  ['ir', 'to go'],
  ['voy', 'I go (present)'],
  ['vas', 'you go (present)'],
  ['van', 'they go (present)'],
  ['yendo', 'going (participle)'],
  ['ido', 'gone (participle)'],
  ['hacer', 'to do/make'],
  ['hago', 'I do/make (present)'],
  ['haces', 'you do/make (present)'],
  ['hacen', 'they do/make (present)'],
  ['haciendo', 'doing/making (participle)'],
  ['hecho', 'done/made (participle)'],
  ['sobre', 'about/on/over'],
  ['tras', 'after/behind/next to'],
  ['mientras', 'while'],
  ['menos', 'less/minus'],
  ['después', 'afterwards'],
  ['también', 'also/too'],
  ['cómo', 'how'],
  ['muy', 'very'],
  ['desde', 'since/from'],
  ['nosotros', 'we/us'],
  ['mucho', 'a lot/much'],
  ['nadie', 'nobody'],
  ['ningún', 'no/none'],
  ['siempre', 'always'],
  ['tan', 'so/as'],
  ['tanto', 'so much/many'],
  ['aquí', 'here'],
  ['cuando', 'when'],
  ['sí', 'yes'],
  ['solo', 'alone/only'],
  ['ayer', 'yesterday'],
  ['todo', 'all/everything'],
  ['hoy', 'today'],
  ['bien', 'well'],
  ['cualquier', 'any/whatever'],
  ['donde', 'where'],
  ['cada', 'each/every'],
  ['hasta', 'until'],
  ['nada', 'nothing'],
  ['aunque', 'although'],
  ['quién', 'who'],
  ['dentro', 'inside/within'],
  ['poco', 'little/few'],
  ['algunos', 'some'],
  ['cosa', 'thing'],
  ['gran', 'great/big'],
  ['antes', 'before'],
  ['tiempo', 'time'],
  ['entre', 'between/among'],
  ['sin', 'without'],
  ['mayor', 'greater/major'],
  ['después de', 'after'],
  ['siquiera', 'even/if'],
  ['vida', 'life'],
  ['contra', 'against'],
  ['mejor', 'better/best'],
  ['uno', 'one'],
  ['dos', 'two'],
  ['tres', 'three'],
  ['cuatro', 'four'],
  ['cinco', 'five'],
  ['seis', 'six'],
  ['siete', 'seven'],
  ['ocho', 'eight'],
  ['nueve', 'nine'],
  ['diez', 'ten'],
  ['cien', 'hundred'],
  ['mil', 'thousand'],
  ['más', 'more'],
  ['menos', 'less'],
  ['alto', 'tall/high'],
  ['bajo', 'short/low'],
  ['joven', 'young'],
  ['viejo', 'old'],
  ['bueno', 'good'],
  ['mal', 'bad'],
  ['feo', 'ugly'],
  ['bonito', 'pretty/nice'],
  ['lindo', 'cute/pretty'],
  ['blanco', 'white'],
  ['negro', 'black'],
  ['rojo', 'red'],
  ['azul', 'blue'],
  ['verde', 'green'],
  ['amarillo', 'yellow'],
  ['gris', 'gray'],
  ['naranja', 'orange'],
  ['rosa', 'pink'],
  ['morado', 'purple'],
  ['mar', 'sea/ocean'],
  ['agua', 'water'],
  ['fuego', 'fire'],
  ['aire', 'air'],
  ['sol', 'sun'],
  ['luna', 'moon'],
  ['tierra', 'earth/land'],
  ['cielo', 'sky/heaven'],
  ['nube', 'cloud'],
  ['viento', 'wind'],
  ['nieve', 'snow'],
  ['lluvia', 'rain'],
  ['árbol', 'tree'],
  ['planta', 'plant'],
  ['flor', 'flower'],
  ['fruta', 'fruit'],
  ['animal', 'animal'],
  ['perro', 'dog'],
  ['gato', 'cat'],
  ['pájaro', 'bird'],
  ['pez', 'fish'],
  ['insecto', 'insect'],
  ['persona', 'person'],
  ['hombre', 'man'],
  ['mujer', 'woman'],
  ['niño', 'child/boy'],
  ['niña', 'child/girl'],
  ['amigo', 'friend'],
  ['familia', 'family'],
  ['padre', 'father'],
  ['madre', 'mother'],
  ['hermano', 'brother'],
  ['hermana', 'sister'],
  ['hijo', 'son'],
  ['hija', 'daughter'],
  ['casa', 'house/home'],
  ['puerta', 'door'],
  ['ventana', 'window'],
  ['mesa', 'table'],
  ['silla', 'chair'],
  ['cama', 'bed'],
  ['ropa', 'clothes'],
  ['zapato', 'shoe'],
  ['comida', 'food'],
  ['bebida', 'drink'],
  ['taza', 'cup/mug'],
  ['plato', 'plate'],
  ['cuchillo', 'knife'],
  ['tenedor', 'fork'],
  ['cuchara', 'spoon'],
  ['libro', 'book'],
  ['periódico', 'newspaper'],
  ['carta', 'letter'],
  ['palabra', 'word'],
  ['número', 'number'],
  ['música', 'music'],
  ['película', 'movie'],
  ['foto', 'photo/picture'],
  ['arte', 'art'],
  ['dinero', 'money'],
  ['trabajo', 'job/work'],
  ['estudio', 'study/learning'],
  ['escuela', 'school'],
  ['universidad', 'university'],
  ['gobierno', 'government'],
  ['país', 'country'],
  ['pueblo', 'town/village'],
  ['carretera', 'road/highway'],
  ['puente', 'bridge'],
  ['tren', 'train'],
  ['avión', 'plane'],
  ['barco', 'boat/ship'],
  ['coche', 'car'],
  ['bicicleta', 'bicycle'],
  ['caminar', 'to walk'],
  ['correr', 'to run'],
  ['nadar', 'to swim'],
  ['viajar', 'to travel'],
  ['escribir', 'to write'],
  ['leer', 'to read'],
  ['hablar', 'to speak/talk'],
  ['escuchar', 'to listen'],
  ['ver', 'to see'],
  ['mirar', 'to look'],
  ['buscar', 'to search/look for'],
  ['encontrar', 'to find'],
  ['comprar', 'to buy'],
  ['vender', 'to sell'],
  ['dar', 'to give'],
  ['recibir', 'to receive'],
  ['llevar', 'to wear/to take'],
  ['usar', 'to use'],
  ['prestar', 'to lend'],
  ['pedir', 'to ask for/to order'],
  ['pagar', 'to pay'],
  ['cobrar', 'to charge'],
  ['trabajar', 'to work'],
  ['estudiar', 'to study'],
  ['aprender', 'to learn'],
  ['enseñar', 'to teach/show'],
  ['saber', 'to know (facts)'],
  ['conocer', 'to know (people/places)'],
  ['querer', 'to want/love'],
  ['amar', 'to love'],
  ['gustar', 'to like'],
  ['disfrutar', 'to enjoy'],
  ['tener', 'to have'],
  ['estar', 'to be (temporary)'],
  ['ser', 'to be (permanent)'],
  ['ir', 'to go'],
  ['venir', 'to come'],
  ['volver', 'to return/come back'],
  ['partir', 'to leave/depart'],
  ['empezar', 'to start/begin'],
  ['terminar', 'to finish/end'],
  ['poder', 'to be able/can'],
  ['deber', 'should/must/ought to'],
  ['querer decir', 'to mean'],
  ['entender', 'to understand'],
  ['creer', 'to believe/think'],
  ['saber', 'to know (how to)'],
  ['tener que', 'to have to/must'],
  ['pensar', 'to think'],
  ['sentir', 'to feel/regret'],
  ['enfadarse', 'to get angry'],
  ['llorar', 'to cry'],
  ['reír', 'to laugh'],
  ['dormir', 'to sleep'],
  ['levantarse', 'to get up'],
  ['vestirse', 'to get dressed'],
  ['bañarse', 'to bathe'],
  ['ducharse', 'to take a shower'],
  ['cepillarse', 'to brush (teeth/hair)'],
  ['cocinar', 'to cook'],
  ['comer', 'to eat'],
  ['beber', 'to drink'],
  ['abrir', 'to open'],
  ['cerrar', 'to close'],
  ['entrar', 'to enter/go in'],
  ['salir', 'to go out/leave'],
  ['correr', 'to run'],
  ['caminar', 'to walk'],
  ['volar', 'to fly'],
  ['nadar', 'to swim'],
  ['jugar', 'to play (a game/sport)'],
  ['cantar', 'to sing'],
  ['bailar', 'to dance'],
  ['tocar', 'to play (an instrument)'],
  ['ver televisión', 'to watch TV'],
  ['escuchar música', 'to listen to music'],
  ['hacer ejercicio', 'to exercise'],
  ['descansar', 'to rest/relax'],
  ['viajar', 'to travel'],
  ['ir de compras', 'to go shopping'],
  ['pasar tiempo con', 'to spend time with'],
  ['conducir', 'to drive'],
  ['subir', 'to go up/get on'],
  ['bajar', 'to go down/get off'],
  ['ir al trabajo', 'to go towork'],
  ['ir a la escuela', 'to go to school'],
  ['ir al supermercado', 'to go to the supermarket'],
  ['ir al cine', 'to go to the movies'],
  ['ir a un restaurante', 'to go to a restaurant'],
  ['ir de vacaciones', 'to go on vacation/holiday'],
  ['ir de fiesta', 'to go partying/out'],
  ['estar enfermo', 'to be sick'],
  ['ir al médico', 'to go to the doctor'],
  ['tomar medicinas', 'to take medicine'],
  ['descubrir', 'to discover'],
  ['desarrollar', 'to develop'],
  ['crecer', 'to grow'],
  ['construir', 'to build'],
  ['destruir', 'to destroy'],
  ['producir', 'to produce'],
  ['consumir', 'to consume'],
  ['resolver', 'to solve'],
  ['mejorar', 'to improve'],
  ['empeorar', 'to worsen'],
  ['mantener', 'to maintain/keep'],
  ['cambiar', 'to change'],
  ['ayudar', 'to help'],
  ['apoyar', 'to support'],
  ['abandonar', 'to abandon/leave'],
  ['pelear', 'to fight'],
  ['ganar', 'to win'],
  ['perder', 'to lose'],
  ['lograr', 'to achieve/succeed'],
  ['fracasar', 'to fail'],
  ['preocuparse', 'to worry'],
  ['ocuparse', 'to take care of/deal with'],
  ['disculparse', 'to apologize'],
  ['perdonar', 'to forgive'],
  ['celebrar', 'to celebrate'],
  ['despedir', 'to say goodbye/farewell'],
  ['saludar', 'to greet/say hello'],
  ['congratular', 'to congratulate'],
  ['dar gracias', 'to thank'],
  ['pedir perdón', 'to ask for forgiveness'],
  ['preguntar', 'to ask (a question)'],
  ['responder', 'to answer/respond'],
  ['explicar', 'to explain'],
  ['contar', 'to tell (a story)'],
  ['mostrar', 'to show/display'],
  ['demostrar', 'to demonstrate/prove'],
  ['comprobar', 'to check/verify'],
  ['preparar', 'to prepare/get ready'],
  ['organizar', 'to organize'],
  ['planificar', 'to plan'],
  ['esperar', 'to wait/hope for'],
  ['encontrar', 'to meet/encounter'],
  ['invitar', 'to invite'],
  ['aceptar', 'to accept'],
  ['rechazar', 'to reject/refuse'],
  ['evitar', 'to avoid'],
  ['escapar', 'to escape/get away'],
  ['ocurrir', 'to happen/occur'],
  ['pasar', 'to happen/pass by'],
  ['dar vueltas', 'to wander around'],
  ['permanecer', 'to stay/remain'],
  ['vivir', 'to live'],
  ['morir', 'to die'],
  ['nacer', 'to be born'],
  ['casarse', 'to get married'],
  ['divorciarse', 'to get divorced'],
  ['enamorarse', 'to fall in love'],
  ['separarse', 'to separate'],
  ['tener hijos', 'to have children'],
  ['criar', 'to raise (children)'],
  ['cuidar', 'to take care of'],
  ['educar', 'to educate'],
  ['tratar', 'to treat/handle'],
  ['acostumbrarse', 'to get used to'],
  ['adaptarse', 'to adapt/adjust'],
  ['cambiar de opinión', "to change one's mind"],
  ['dar la razón', 'to agree'],
  ['discrepar', 'to disagree'],
  ['convencer', 'to convince'],
  ['engañar', 'to deceive/cheat'],
  ['mentir', 'to lie'],
  ['confiar', 'to trust'],
  ['sospechar', 'to suspect'],
  ['disculparse', 'to apologize'],
  ['perdonar', 'to forgive'],
  ['negociar', 'to negotiate'],
  ['comprar', 'to buy'],
  ['vender', 'to sell'],
  ['pagar', 'to pay'],
  ['cobrar', 'to charge/collect (money)'],
  ['ahorrar', 'to save (money)'],
  ['gastar', 'to spend (money)'],
  ['invertir', 'to invest'],
  ['alquilar', 'to rent'],
  ['prestar', 'to lend'],
  ['pedir prestado', 'to borrow'],
  ['devolver', 'to return (something)'],
  ['regalar', 'to give (as a gift)'],
  ['enviar', 'to send'],
  ['recibir', 'to receive'],
  ['abrir', 'to open'],
  ['cerrar', 'to close/shut'],
  ['entrar', 'to enter/go in'],
  ['salir', 'to go out/exit'],
  ['correr', 'to run'],
  ['caminar', 'to walk'],
  ['conducir', 'to drive'],
  ['montar en bicicleta', 'to ride a bicycle'],
  ['nadar', 'to swim'],
  ['saltar', 'to jump'],
  ['bailar', 'to dance'],
  ['cantar', 'to sing'],
  ['tocar un instrumento', 'to play an instrument'],
  ['pintar', 'to paint'],
  ['dibujar', 'to draw'],
  ['escribir', 'to write'],
  ['leer', 'to read'],
  ['estudiar', 'to study'],
  ['enseñar', 'to teach/show'],
  ['aprender', 'to learn'],
  ['trabajar', 'to work'],
  ['descansar', 'to rest/relax'],
  ['dormir', 'to sleep'],
  ['comer', 'to eat'],
  ['beber', 'to drink'],
  ['cocinar', 'to cook'],
  ['hornear', 'to bake'],
  ['limpiar', 'to clean'],
  ['lavar', 'to wash'],
  ['secar', 'to dry'],
  ['planchar', 'to iron'],
  ['cortar', 'to cut'],
  ['peinar', 'to comb (hair)'],
  ['cepillar', 'to brush (teeth/hair)'],
  ['vestir', 'to dress/wear'],
  ['desvestir', 'to undress'],
  ['bañarse', 'to take a bath/shower'],
  ['afeitarse', 'to shave'],
  ['maquillarse', 'to put on makeup'],
  ['cepillarse los dientes', "to brush one's teeth"],
  ['reír', 'to laugh'],
  ['llorar', 'to cry'],
  ['gritar', 'to shout/scream'],
  ['suspirar', 'to sigh'],
  ['mirar', 'to look/watch'],
  ['ver', 'to see'],
  ['escuchar', 'to listen (to)'],
  ['oler', 'to smell'],
  ['tocar', 'to touch/play (an instrument)'],
  ['sentir', 'to feel/sense'],
  ['tener miedo', 'to be afraid'],
  ['sentirse bien/mal', 'to feel well/bad'],
  ['estar feliz/triste', 'to be happy/sad'],
  ['enojarse', 'to get angry'],
  ['preocuparse', 'to worry'],
  ['estar cansado', 'to be tired'],
  ['tener hambre/sed', 'to be hungry/thirsty'],
  ['estar enfermo', 'to be sick'],
  ['tener frío/calor', 'to be cold/hot'],
  ['estar aburrido', 'to be bored'],
  ['tener sueño', 'to be sleepy'],
  ['estar ocupado', 'to be busy'],
  ['tener prisa', 'to be in a hurry'],
  ['estar emocionado', 'to be excited'],
  ['tener razón', 'to be right'],
  ['estar equivocado', 'to be wrong'],
  ['tener suerte', 'to be lucky'],
  ['estar de acuerdo', 'to agree'],
  ['estar en desacuerdo', 'to disagree'],
  ['estar seguro/inseguro', 'to be sure/unsure'],
  ['estar listo', 'to be ready'],
  ['estar terminado', 'to be finished'],
  ['estar en casa', 'to be at home'],
  ['estar en el trabajo', 'to be at work'],
  ['estar de vacaciones', 'to be on vacation/holiday'],
  ['estar de viaje', 'to be on a trip/journey'],
  ['estar en el colegio/universidad', 'to be at school/university'],
  ['ser', 'to be (permanent characteristic)'],
  ['estar', 'to be (temporary state)'],
  ['tener', 'to have'],
  ['hacer', 'to do/make'],
  ['querer', 'to want/love'],
  ['poder', 'to be able/can'],
  ['saber', 'to know (information)'],
  ['conocer', 'to know (a person/place)'],
  ['decir', 'to say/tell'],
  ['ver', 'to see/watch'],
  ['dar', 'to give'],
  ['llevar', 'to carry/wear'],
  ['poner', 'to put/place'],
  ['venir', 'to come'],
  ['ir', 'to go'],
  ['estar', 'to be'],
  ['haber', 'to have (auxiliary verb)'],
  ['sí', 'yes'],
  ['no', 'no'],
  ['bien', 'well/good'],
  ['mal', 'bad/poorly'],
  ['me', 'me'],
  ['te', 'you (singular informal)'],
  ['él', 'he'],
  ['ella', 'she'],
  ['usted', 'you (singular formal)'],
  ['nosotros/nosotras', 'we'],
  ['vosotros/vosotras', 'you all (informal)'],
  ['ellos/ellas', 'they'],
  ['ustedes', 'you all (formal)'],
  ['este/esta', 'this (masculine/feminine)'],
  ['ese/esa', 'that (masculine/feminine)'],
  ['aquel/aquella', 'that (over there) (masculine/feminine)'],
  ['aquí', 'here'],
  ['ahí', 'there (nearby)'],
  ['allí', 'there (far away)'],
  ['allá', 'over there (far away)'],
  ['mucho', 'a lot/much'],
  ['poco', 'a little/few'],
  ['más', 'more'],
  ['menos', 'less'],
  ['todo/toda', 'all/everything (masculine/feminine)'],
  ['nada', 'nothing'],
  ['alguno/alguna', 'some/any (masculine/feminine)'],
  ['ninguno/ninguna', 'none/not any (masculine/feminine)'],
  ['mismo/misma', 'same (masculine/feminine)'],
  ['otro/otra', 'other/another (masculine/feminine)'],
  ['varios/varias', 'several/various (masculine/feminine)'],
  ['bueno/buena', 'good (masculine/feminine)'],
  ['malo/mala', 'bad (masculine/feminine)'],
  ['grande', 'big/large'],
  ['pequeño/pequeña', 'small/little (masculine/feminine)'],
  ['bonito/bonita', 'pretty/nice (masculine/feminine)'],
  ['feo/fea', 'ugly (masculine/feminine)'],
  ['alto/alta', 'tall/high (masculine/feminine)'],
  ['bajo/baja', 'short/low (masculine/feminine)'],
  ['joven', 'young'],
  ['viejo/vieja', 'old (masculine/feminine)'],
  ['nuevo/nueva', 'new (masculine/feminine)'],
  ['viejo/nuevo', 'old/new'],
  ['primero/primera', 'first (masculine/feminine)'],
  ['último/última', 'last (masculine/feminine)'],
  ['mejor', 'better/best'],
  ['peor', 'worse/worst'],
  ['mayor', 'older/oldest/larger/largest'],
];
